@startuml
left to right direction
actor Cliente as clien


rectangle "sistema" {
    usecase "factura Cliente" as Facturacleinte
    usecase "deatlle factura" as Dettalefactura
    usecase "producto" as Producto
    usecase "ingresar producto" as Ingresarproducto
    usecase "inventario" as Inventario
    usecase "ingresar inventario" as Ingresarinventario
    
}

clien --> Facturacleinte
clien --> Dettalefactura
clien --> Producto
clien --> Ingresarproducto
clien --> Inventario
clien --> Ingresarinventario

System --> Facturacleinte
System --> Dettalefactura
System --> Producto
System --> Ingresarproducto
System --> Inventario
System --> Ingresarinventario




@enduml